---

- name: Install webhook
  package:
    name: "webhook{{ webhook_version }}"
    state: present

- name: Add optional arguments if there are any
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/webhook.service
    regexp: '^ExecStart='
    line: "ExecStart=/usr/bin/webhook -nopanic -hooks /etc/webhook.conf -port {{ webhook_port }} {{ optional_args }}"
  when: optional_args is defined
