---
- name: Add group "webhook"
  become: true
  group:
    name: "{{ webhook_group }}"

- name: Add webhook user
  become: true
  user:
    name: "{{ webhook_user }}"
    group: "{{ webhook_group }}"
    groups: "{{ webhook_extra_groups }}"
    home: /var/webhook
    shell: /bin/false

# Copy webhooks hook file
- name: Copy webhook hooks.json file
  become: true
  template:
    src: templates/hooks.json.j2
    dest: "/etc/webhooks.json"
    owner: "{{ webhook_user }}"
    group: "{{ webhook_group }}"
    mode: u=rw,g=r,o=r

# include OS Specific Tasks.
- include_tasks: "{{ ansible_os_family }}.yml"
