---
- name: Converge
  hosts: all
  become: true

  vars:
    webhook_groups:
      - ssl-certs
    githubhooks:
      - id: "redeploy-webhook-github"
        cmd: "./reload.sh"
        cwd: "/var/"
        branch: master
        token: supersecretpassword
        args:
          - source: "url"
            name: "name"
    gitlabhooks:
      - id: "redeploy-webhook-gitlab"
        cmd: "./reload.sh"
        cwd: "/var/"
        branch: ''
        token: supersecretpassword
        args:
          - source: "url"
            name: "name"
    httphooks:
      - id: "test id"
        cmd: "./reload.sh"
        cwd: "/var/"
        responseMsg: "hello, world"
        branch: master
        token: secretsuper

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-webhook
